### ISSUE TITLE
del clone đc

### ISSUE THREAD

**Issue by HoaiNam007** [longtran2629/xd-pm-web#3]

**Comment by longtran2629** [comment]
cái git desktop à, thử lại xem, hoặc code ít quá thì paste qua discord t
live sửa cho


Vào CN, 11 thg 4, 2021 vào lúc 22:34 HoaiNam007 ***@***.***>
đã viết:

**Comment by longtran2629** [comment]
clone bt mà, clone về m giải nén cái của m thôi, sửa lại r nén lại cái file
nén chính (gồm bài t - báo cáo - yours)

Vào CN, 11 thg 4, 2021 vào lúc 22:38 Jay ***@***.***> đã viết:

**Comment by longtran2629** [comment]
hoặc làm như cũ, clone main về up lên nhánh, tí merge lại

Vào CN, 11 thg 4, 2021 vào lúc 22:40 Jay ***@***.***> đã viết:
